services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Psr\Log\LoggerInterface:
    class: Monolog\Logger
    arguments: ['app']

  Tax16\SystemCheckBundle\:
    resource: '../../../*'
    exclude: '../../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Tax16\SystemCheckBundle\Core\Domain\Port\ApplicationLoggerInterface:
    class: Tax16\SystemCheckBundle\Infrastructure\Logger\PsrLoggerAdapter
    arguments:
      - '@Psr\Log\LoggerInterface'