version: '3.8'

services:
  php74:
    build:
      context: .docker/php74
    container_name: php74
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - test-network

  php81:
    build:
      context: .docker/php81
    container_name: php81
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - test-network

networks:
  test-network:

volumes:
  mysql-data:
