version: '3.8'

services:
  php74:
    build:
      context: .docker/php74
    container_name: php74
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - test-network
    depends_on:
      - db

  php81:
    build:
      context: .docker/php81
    container_name: php81
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - test-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    networks:
      - test-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  test-network:

volumes:
  mysql-data:
