system_ping:
  path: /system-check/ping
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::ping
system_check_dashboard:
  path: /system-check/dashboard
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::checkDashboard
system_health_json:
  path: /system-check/health
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::healthJson
system_health:
  path: /system-check/health
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::health
