system_index:
  path: /system-check/index
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::index
system_details:
  path: /system-check/details
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::details
system_health_json:
  path: /system-check/health
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::healthJson
system_health:
  path: /system-check/health
  controller: Tax16\SystemCheckBundle\Controller\SystemCheckController::health
