services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Tax16\SystemCheckBundle\Controller\SystemCheckController:
    tags: ['controller.service_arguments']

  Tax16\SystemCheckBundle\Services\Health\HealthCheckManager:
    arguments:
      - !tagged_iterator system_check.health_check
      - '@logger'

  Tax16\SystemCheckBundle\DependencyInjection\HealthCheckCompilerPass:
    tags:
      - { name: 'kernel.compiler_pass', priority: 10 }