services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Tax16\SystemCheckBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Tax16\SystemCheckBundle\Controller\SystemCheckController:
    tags: ['controller.service_arguments']
